<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
$form = $this->changePasswordForm;
$form->prepare();
$form->setAttribute('action', $this->url('bpl-user/change-password'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>
<h1><?= $this->translate('Change Password') ?></h1>
<?= $this->partial('bpl-user/generic-form', ['form' => $form]) ?>