<?php
/**
 * 
 * @author Bishwo Prasad Lamichhane <bishwo.prasad@gmail.com>
 */
$form = $this->changeProfileForm;
$form->prepare();
$form->setAttribute('action', $this->url('bpl-user/change-profile'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>
<h1><?= $this->translate('Change Profile') ?></h1>
<?php if ($this->profileChanged == true) : ?>
    <p><?= $this->translate("Your profile has been changed succesfully") ?></p>
<?php endif; ?>
<?= $this->partial('bpl-user/generic-form', ['form' => $form]) ?>