<?php
/**
 * 
 * @author Bishwo Prasad Lamichhane <bishwo.prasad@gmail.com>
 */
?>

<?php if ($this->sent == true) { ?>
    <h1><?php echo $this->translate('Forgot your password?'); ?></h1>

    <p><?php echo sprintf($this->translate('A reminder has been sent to your e-mail address %s. Follow instructions in the email to reset your password.'), $this->escapeHtml($this->email)); ?></p>

    <a href="<?php echo $this->url('bpl-user/login') ?>"><?php echo $this->translate('Back to login?'); ?></a>
<?php } else { ?>

    <h1><?= $this->translate('Forgot your password?') ?></h1>

    <?php
    $form = $this->forgotPasswordForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('bpl-user/forgot-password'));
    $form->setAttribute('method', 'post');
    $form->setAttribute('autocomplete', 'off');
    ?>

    <?= $this->partial('bpl-user/generic-form', ['form' => $form]) ?>

    <a href="<?php echo $this->url('bpl-user/login') ?>"><?php echo $this->translate('Back to login.'); ?></a>
    <?php
}