<?php
/**
 * 
 * @author Bishwo Prasad Lamichhane <bishwo.prasad@gmail.com>
 */
?>
<h1><?= $this->translate('Reset Password') ?></h1>
<small>for <?= $resetRecord->getUser()->getEmail() ?></small>
<p></p>
<?php
$form = $this->resetPasswordForm;
$form->prepare();
$form->setAttribute('action', $this->url('bpl-user/reset-password', [
            'userId' => $resetRecord->getUser()->getId(), 'token' => $resetRecord->getRequestKey()
]));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>

<?= $this->partial('bpl-user/generic-form', ['form' => $form]) ?>

<a href="<?php echo $this->url('bpl-user/login') ?>"><?php echo $this->translate('Back to login'); ?></a>