<?= $this->form()->openTag($form) ?>
    <dl class="zend_form">
        <?php foreach ($form as $element): ?>
            <?php if ($element->getLabel() != null && !$element instanceof \Laminas\Form\Element\Button): ?>
                <dt><?= $this->formLabel($element) ?></dt>
            <?php elseif($element instanceof \Laminas\Form\Element\Button): ?>
                <dt><label> </label></dt>
            <?php endif ?>
            <dd><?= $this->formElement($element) . $this->formElementErrors($element) ?></dd>
        <?php endforeach ?>
    </dl>
<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>">
<?php endif ?>
<?= $this->form()->closeTag() ?>