<?php if ($this->registered == true) { ?>
    <h1>Registration Successful</h1>
    <p>
        <?=
        sprintf($this->translate("Registration has been successful. "
                        . "An activation link has been sent to your email address %s. "
                        . "Please check your email to activate your account. "
                        . "Make sure to check Spam folder in your mail "
                        . "account if activation link is not in your "
                        . "Inbox."), '<strong>' . $this->escapeHtml($this->user->getEmail()) . '</strong>')
        ?>
    </p>
    <p>
        <a href="<?php echo $this->url('bpl-user/login') ?>"><?php echo $this->translate('Back to login'); ?></a>
    </p>
<?php } else { ?>
    <h1><?= $this->translate('Register') ?></h1>

    <?php
    $form = $this->registerForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('bpl-user/register'));
    $form->setAttribute('method', 'post');
    $form->setAttribute('autocomplete', 'off');
    ?>

    <?= $this->partial('bpl-user/generic-form', ['form' => $form]) ?>

    <a href="<?php echo $this->url('bpl-user/login') ?>">
        <?php echo $this->translate('I already have an account'); ?>
    </a>
    <?php
}