<?php
/**
 * 
 * @author Bishwo Prasad Lamichhane <bishwo.prasad@gmail.com>
 */
?>
<h1>Registration Successful</h1>
<p>
    <?=
    sprintf($this->translate("Registration has been successful. "
                    . "An activation link has been sent to your email address %s. "
                    . "Please check your email to activate your account. "
                    . "Make sure to check Spam folder in your mail "
                    . "account if activation link is not in your "
                    . "Inbox."), '<strong>'.$this->escapeHtml($this->user->getEmail()).'</strong>')
    ?>
</p>
<p>
    <a href="<?php echo $this->url('bpl-user/login') ?>"><?php echo $this->translate('Back to login'); ?></a>
</p>